menu:
  首页: /
  技术: /categories/tech/
  生活: /categories/life/
  归档: /archives

widgets:
- search
- tag
- recent_posts
- category
- tagcloud
- weibo


excerpt_link: Read More

twitter:
  username:
  show_replies: false
  tweet_count: 5

addthis:
  enable: false
  pubid:
  weibo: 

copyright:
  enable: false
  claim: 版权声明：自由转载-非商用-无演绎-保持署名 @ Creative Commons BY-NC-ND 3.0
  show_link: true

fancybox: true

google_analytics: UA-45019001-1
analytics_site_name: topdna.org
rss: